export const login = '/Login'
export const registration = '/registration'
export const profile = '/Profile'
export const notPage = '/404'
export const restorePass = '/RestorePage'
export const newPass = '/NewPass'
export const PackCards = '/PackCard'
