export const LoginPage = '/Login'
export const RegistrationPage = '/registration'
export const ProfilePage = '/Profile'
export const NotPage = '/404'
export const RestorePassPage = '/RestorePage'
export const NewPassPage = '/NewPass'
export const PackCardsPage = '/PackCard'
